package main

import (
	"os"
	"strings"
	"testing"
)

// TestRedaction is the fixture required by PLAN.md 1d: a string containing each
// pattern comes out fully redacted with surrounding prose intact.
func TestRedaction(t *testing.T) {
	// One representative hit per pattern, embedded in prose. Each non-secret
	// word must survive; every secret must collapse to exactly [REDACTED].
	const input = `Before anything, the key was sk-live12345678901234567890.
Then we set GH_TOKEN=ghp_0123456789abcdef0123456789abcdef0123.
The fine-grained PAT github_pat_11ABCD2EFGHIJKLMNOPQRSTUVWXYZ_qwerty was also leaked.
AWS had AKIAIOSFODNN7EXAMPLE attached to the box.
Slack token xoxb-1234567890-abcdef sits in env.
The DB url is postgres://user:sup3rs3cret@db.example.com:5432/app?sslmode=disable
or mysql://app:hunter2@10.0.0.5:3306/svc for the legacy shard.
Auth header was Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.payload.sig
and the signing key was:
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAabcd1234FAKEKEYf0rTestingPurposesOnlyDoNotUseReal
-----END RSA PRIVATE KEY-----
After all that, we shipped the auth feature.`

	got := redact(input)

	// Surrounding prose must survive (a sampling of sentences).
	for _, want := range []string{
		"Before anything, the key was",
		"Then we set GH_TOKEN=",
		"AWS had",
		"Slack token",
		"The DB url is",
		"Auth header was",
		"After all that, we shipped the auth feature.",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("prose dropped by redaction: missing %q\n got: %s", want, got)
		}
	}

	// No secret material may survive. Each of these fragments appears in the
	// input but must NOT appear in the output.
	for _, leaked := range []string{
		"sk-live12345678901234567890",
		"ghp_0123456789abcdef0123456789abcdef0123",
		"github_pat_11ABCD2EFGHIJKLMNOPQRSTUVWXYZ_qwerty",
		"AKIAIOSFODNN7EXAMPLE",
		"xoxb-1234567890-abcdef",
		"sup3rs3cret",
		"hunter2",
		"eyJhbGciOiJIUzI1NiJ9.payload.sig",
		"MIIEpAIBAAKCAQEAabcd1234FAKEKEYf0rTestingPurposesOnlyDoNotUseReal",
		"MIIEpAIBAA",
	} {
		if strings.Contains(got, leaked) {
			t.Errorf("secret survived redaction: %q\n got: %s", leaked, got)
		}
	}

	// Every secret must have been replaced with the literal token. Count must
	// match the number of patterns fired (9: one each per pattern, with two DB
	// URLs counted separately — postgres + mysql). We check by ensuring each
	// replacement site is present.
	wantRedactions := 9
	if c := strings.Count(got, "[REDACTED]"); c != wantRedactions {
		t.Errorf("expected %d [REDACTED] tokens, got %d\n got: %s", wantRedactions, c, got)
	}
}

func TestRedactionKeepsNonSecretsUntouched(t *testing.T) {
	in := "plain text with no secrets, just sk-mentioned as a substring"
	out := redact(in)
	if out != in {
		t.Errorf("non-secret text modified:\n in:  %q\n out: %q", in, out)
	}
}

// --- turn-fusing / short-turn logic ---

func TestIsShortTurn(t *testing.T) {
	cases := []struct {
		in   string
		want bool
	}{
		{"ok", true},
		{"OK", true},
		{"yes", true},
		{"Go ahead", true},
		{"continue", true},
		{"please", true},
		{"", true},
		{"short", true}, // under 40 chars
		{"this is a perfectly normal turn that exceeds forty characters", false},
		{"another much longer turn that is definitely over the threshold limit", false},
	}
	for _, c := range cases {
		if got := isShortTurn(c.in, shortTurnChars); got != c.want {
			t.Errorf("isShortTurn(%q) = %v, want %v", c.in, got, c.want)
		}
	}
}

func TestIsNoise(t *testing.T) {
	for _, in := range []string{
		"<command-name>bash</command-name>",
		"<local-command-stdout>output</local-command-stdout>",
		"<system-reminder>you are a helpful assistant</system-reminder>",
		"Caveat: The messages below were generated by the user while running local commands.",
	} {
		if !isNoise(in) {
			t.Errorf("isNoise(%q) = false, want true", in)
		}
	}
	for _, in := range []string{
		"how do I fix the auth bug?",
		"  trimmed text",
		"",
	} {
		if isNoise(in) {
			t.Errorf("isNoise(%q) = true, want false", in)
		}
	}
}

func TestFuseTurn(t *testing.T) {
	got := fuseTurn("why did we pick bcrypt?", "because argon2 wasn't available", []string{"Read", "Edit", "Read"})
	want := "User: why did we pick bcrypt?\nAssistant: because argon2 wasn't available\nTools: Read, Edit"
	if got != want {
		t.Errorf("fuseTurn with tools:\n got: %q\n want: %q", got, want)
	}

	// No tools, no assistant.
	got = fuseTurn("just a user", "", nil)
	if got != "User: just a user" {
		t.Errorf("fuseTurn minimal: got %q", got)
	}
}

// --- jsonl parsing ---

func TestUserTextString(t *testing.T) {
	ev, ok := parseEntry([]byte(`{"type":"user","uuid":"u1","cwd":"/x/y","timestamp":"2025-01-02T15:04:05Z","message":{"role":"user","content":"hello there"}}`))
	if !ok {
		t.Fatal("expected ok")
	}
	if !ev.isUser || ev.userText != "hello there" {
		t.Errorf("got %+v", ev)
	}
}

func TestUserTextBlocks(t *testing.T) {
	ev, ok := parseEntry([]byte(`{"type":"user","message":{"role":"user","content":[{"type":"text","text":"line one"},{"type":"tool_result","content":"ignored"}]}}`))
	if !ok {
		t.Fatal("expected ok")
	}
	if ev.userText != "line one" {
		t.Errorf("got %q (tool_result must not leak)", ev.userText)
	}
}

func TestUserTextDropsToolResultOnly(t *testing.T) {
	_, ok := parseEntry([]byte(`{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"x"}]}}`))
	if ok {
		t.Error("tool_result-only user entry must be dropped")
	}
}

func TestUserTextDropsNoise(t *testing.T) {
	_, ok := parseEntry([]byte(`{"type":"user","message":{"role":"user","content":"<command-name>bash</command-name>"}}`))
	if ok {
		t.Error("noise entry must be dropped")
	}
}

func TestAssistantParts(t *testing.T) {
	ev, ok := parseEntry([]byte(`{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"hi"},{"type":"tool_use","name":"Read","input":{}}]}}`))
	if !ok {
		t.Fatal("expected ok")
	}
	if ev.asstText != "hi" {
		t.Errorf("asstText=%q", ev.asstText)
	}
	if len(ev.tools) != 1 || ev.tools[0] != "Read" {
		t.Errorf("tools=%v", ev.tools)
	}
}

func TestParseEntrySkipsUnknown(t *testing.T) {
	for _, line := range []string{
		`{"type":"system","message":{"role":"user","content":"x"}}`,
		`not json at all`,
		`{}`,
	} {
		if _, ok := parseEntry([]byte(line)); ok {
			t.Errorf("should have skipped %q", line)
		}
	}
}

// --- extraction end-to-end on a synthetic session ---

func TestExtractFileEndToEnd(t *testing.T) {
	// Two turns:
	//  1. normal: user asks → assistant answers + tool
	//  2. short approval: should borrow turn 1's assistant text
	const session = `{"type":"user","uuid":"u1","cwd":"/home/u/myrepo","timestamp":"2025-01-02T15:04:05Z","message":{"role":"user","content":"how do I configure the database connection?"}}
{"type":"assistant","uuid":"a1","timestamp":"2025-01-02T15:04:06Z","message":{"role":"assistant","content":[{"type":"text","text":"Use the DATABASE_URL env var."},{"type":"tool_use","name":"Read","input":{}}]}}
{"type":"user","uuid":"u2","cwd":"/home/u/myrepo","timestamp":"2025-01-02T15:05:00Z","message":{"role":"user","content":"ok"}}
{"type":"assistant","uuid":"a2","timestamp":"2025-01-02T15:05:01Z","message":{"role":"assistant","content":[{"type":"text","text":"Great, marking done."}]}}
`
	tmp := t.TempDir() + "/s.jsonl"
	mustWrite(t, tmp, session)

	units, err := extractFile(tmp, "sessionA", shortTurnChars)
	if err != nil {
		t.Fatal(err)
	}
	if len(units) != 2 {
		t.Fatalf("expected 2 units, got %d: %+v", len(units), units)
	}

	// Unit 0: normal fused turn.
	u0 := units[0]
	if !strings.HasPrefix(u0.Text, "User: how do I configure") {
		t.Errorf("u0 text: %q", u0.Text)
	}
	if !strings.Contains(u0.Text, "Assistant: Use the DATABASE_URL") {
		t.Errorf("u0 missing assistant: %q", u0.Text)
	}
	if !strings.Contains(u0.Text, "Tools: Read") {
		t.Errorf("u0 missing tools: %q", u0.Text)
	}
	if u0.Repo != "myrepo" {
		t.Errorf("u0 repo=%q want myrepo", u0.Repo)
	}
	if u0.TS != 1735830245 {
		t.Errorf("u0 ts=%d want 1735830245 (2025-01-02T15:04:05Z)", u0.TS)
	}

	// Unit 1: short turn that borrowed the previous assistant message.
	u1 := units[1]
	if !strings.HasPrefix(u1.Text, "Assistant: Use the DATABASE_URL") {
		t.Errorf("u1 should start with borrowed assistant: %q", u1.Text)
	}
	if !strings.Contains(u1.Text, "User: ok") {
		t.Errorf("u1 should still contain the approval: %q", u1.Text)
	}

	// ids must be deterministic.
	id0 := sha256Hex("sessionA:u1")
	if units[0].ID != id0 {
		t.Errorf("u0 id=%q want %q", units[0].ID, id0)
	}
}

func TestShortTurnWithNoPrecedingAssistantDropped(t *testing.T) {
	// A short approval with nothing before it must be dropped, not panic.
	const session = `{"type":"user","uuid":"u1","message":{"role":"user","content":"ok"}}
{"type":"assistant","uuid":"a1","message":{"role":"assistant","content":[{"type":"text","text":"done"}]}}
`
	tmp := t.TempDir() + "/s.jsonl"
	mustWrite(t, tmp, session)
	units, err := extractFile(tmp, "sessionB", shortTurnChars)
	if err != nil {
		t.Fatal(err)
	}
	if len(units) != 0 {
		t.Errorf("expected short-turn-with-no-prior-asst dropped, got %d: %+v", len(units), units)
	}
}

func TestRedactInExtractedUnit(t *testing.T) {
	// Redaction runs at ingest, so a leaked key in a user turn ends up [REDACTED].
	const session = `{"type":"user","uuid":"u1","cwd":"/r","timestamp":"2025-01-02T15:04:05Z","message":{"role":"user","content":"the key is sk-live12345678901234567890 right?"}}
`
	tmp := t.TempDir() + "/s.jsonl"
	mustWrite(t, tmp, session)
	units, _ := extractFile(tmp, "s", shortTurnChars)
	if len(units) != 1 {
		t.Fatalf("got %d units", len(units))
	}
	if strings.Contains(units[0].Text, "sk-live12345678901234567890") {
		t.Errorf("key leaked into unit: %q", units[0].Text)
	}
	if !strings.Contains(units[0].Text, "[REDACTED]") {
		t.Errorf("expected [REDACTED] in unit: %q", units[0].Text)
	}
}

// --- helpers / encoding ---

func TestEncodeDecodeFloats(t *testing.T) {
	in := []float32{0.1, -0.2, 1.5, 0, -1234.5}
	out := decodeFloats(encodeFloats(in))
	if len(out) != len(in) {
		t.Fatalf("len %d vs %d", len(out), len(in))
	}
	for i := range in {
		if out[i] != in[i] {
			t.Errorf("[%d] %v vs %v", i, out[i], in[i])
		}
	}
}

func TestRepoOf(t *testing.T) {
	cases := map[string]string{
		"/home/raffy/myrepo":    "myrepo",
		"C:\\Users\\raffy\\app": "app",
		"/r":                    "r",
		"trailing/slash/":       "slash",
		"":                      "",
	}
	for in, want := range cases {
		if got := repoOf(in); got != want {
			t.Errorf("repoOf(%q)=%q want %q", in, got, want)
		}
	}
}

func TestCosine(t *testing.T) {
	if got := cosine([]float32{1, 0, 0}, []float32{1, 0, 0}); got != 1 {
		t.Errorf("identical: got %v want 1", got)
	}
	if got := cosine([]float32{1, 0, 0}, []float32{0, 1, 0}); got != 0 {
		t.Errorf("orthogonal: got %v want 0", got)
	}
	if got := cosine([]float32{}, []float32{}); got != 0 {
		t.Errorf("empty: got %v want 0", got)
	}
}

func TestSearchRows(t *testing.T) {
	rows := []memory{
		{ID: "a", Vector: []float32{1, 0}, Repo: "x"},
		{ID: "b", Vector: []float32{0, 1}, Repo: "y"},
	}
	hits := searchRows(rows, []float32{1, 0}, "x", 2, repoBoost)
	if hits[0].Mem.ID != "a" {
		t.Errorf("expected a first, got %s", hits[0].Mem.ID)
	}
	// same-repo boost: a is repo x, query repo x → boosted above its raw cosine.
	if hits[0].Score <= 1.0 {
		t.Errorf("boost not applied: score=%v", hits[0].Score)
	}
}

func TestTruncateRunes(t *testing.T) {
	if got := truncateRunes("hello", 10); got != "hello" {
		t.Errorf("no truncation expected, got %q", got)
	}
	if got := truncateRunes("héllo wörld", 5); got != "héllo" {
		// rune-aware, not byte-aware
		t.Errorf("rune truncation: got %q", got)
	}
}

func mustWrite(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// --- eval: golden parsing + rank matching ---

func TestParseGolden(t *testing.T) {
	tmp := t.TempDir() + "/g.txt"
	mustWrite(t, tmp, `# header comment

how did we pick bcrypt ||| because argon2
what about figma ||| capture-widget

# trailing comment
`)
	items, err := parseGolden(tmp)
	if err != nil {
		t.Fatal(err)
	}
	if len(items) != 2 {
		t.Fatalf("expected 2 items (comments/blanks skipped), got %d: %+v", len(items), items)
	}
	if items[0].Query != "how did we pick bcrypt" || items[0].Expect != "because argon2" {
		t.Errorf("item0 wrong: %+v", items[0])
	}
	if items[1].Query != "what about figma" || items[1].Expect != "capture-widget" {
		t.Errorf("item1 wrong: %+v", items[1])
	}
}

func TestParseGoldenRejectsMalformed(t *testing.T) {
	tmp := t.TempDir() + "/g.txt"
	mustWrite(t, tmp, "good query ||| good expect\nno separator here\n")
	_, err := parseGolden(tmp)
	if err == nil {
		t.Error("expected error for missing ||| separator")
	}
}

func TestParseGoldenRejectsEmpty(t *testing.T) {
	tmp := t.TempDir() + "/g.txt"
	mustWrite(t, tmp, " ||| \n")
	_, err := parseGolden(tmp)
	if err == nil {
		t.Error("expected error for empty query and expectation")
	}
}

func TestParseGoldenMissingFile(t *testing.T) {
	_, err := parseGolden(t.TempDir() + "/does-not-exist.txt")
	if err == nil {
		t.Error("expected error for missing file")
	}
}

func TestFindRank(t *testing.T) {
	hits := []hit{
		{Mem: memory{Text: "we used Postgres for the metadata store"}, Raw: 0.9, Score: 0.9},
		{Mem: memory{Text: "auth goes through the env password"}, Raw: 0.7, Score: 0.7},
		{Mem: memory{Text: "unrelated note"}, Raw: 0.5, Score: 0.5},
	}
	if r := findRank(hits, "env password"); r != 2 {
		t.Errorf("expected rank 2, got %d", r)
	}
	if r := findRank(hits, "POSTGRES"); r != 1 { // case-insensitive
		t.Errorf("case-insensitive: expected rank 1, got %d", r)
	}
	if r := findRank(hits, "not present"); r != 0 {
		t.Errorf("expected miss (0), got %d", r)
	}
}
